### ISSUE TITLE
tty2pico not working with 

### ISSUE THREAD

**Issue by kupofgc** [neil-morrison44/MiSTer_tty2pico#2]
Hey everyone,

Really excited to finish my MiSTer build when all the parts eventually arrive. Until then, I am trying to get tty2pico to work ahead of time and I've found myself stuck. Here is everything I have done. I'll try to be specific as possible. 

- Bought [this board](https://thepihut.com/products/raspberry-pi-pico?src=raspberrypi). Pi Pico H with headers.
- Bought [this LCD](https://shop.pimoroni.com/products/pico-display-pack?variant=32368664215635).
- Installed the tty2oled_cc and update_tty2oled scripts off the Github. Both are in my scripts folder and run fine. 
- Downloaded [this firmware](https://micropython.org/download/rp2-pico/) for the Pico board. rp2-pico-20220618-v1.19.1.uf2
- Held BOOTSEL and plugged in the PICO board. Showed as a drive with "INDEX" and "INFO_U2" files. Drag and dropped the downloaded firmware file onto the drive. It unmounts automatically.

From here, I don't know what to do next or how I can confirm I've done the correct steps. After adding the .uf2 firmware, the Pico board automatically unmounts from Windows. After that, I can't get it show up as blank flash drive as the instructions state and I don't know why. The only way to see the drive again is to hold down "BOOTSEL". Once doing that, I can see the contents of the Pico again, but the firmware that I've added is no longer there. When I try to manually add the files from the Github, those disappear as well.

On the Github page, I am clicking on the green "Code" button and the selecting "Download ZIP." From there I extract the contents  and place the folder "MiSTer_tty2pico-main" onto the Pico drive. Please let me know if that sounds right as well.

At this point, I haven't altered any of the tty2oled files as instructed as I don't know howto access those either. I was waiting on that next step as I can't seem to get teh firmware loaded properly onto my Pico H board. I am going to try some previous firmwares to see if they work.

This is an insanely awesome project and I hope we can all figure this out together moving forward. Thanks!

**Comment by kupofgc** [comment]
Just saw this on the installation page: On a computer, plug it into USB with BOOTSEL held (normal Pi Pico firmware.uf2 steps, **_except with the custom firmware from github releases)_**

Am I transferring the wrong .uf2? I don't see a custom .uf2 anywhere in the Github files.

**Comment by neil-morrison44** [comment]
Ah - that’ll be it, it’s here: https://github.com/neil-morrison44/MiSTer_tty2pico/releases/tag/v1.0.0

**Comment by kupofgc** [comment]
Perfect, just flashed it and the board reappeared as a flash drive! Moving forward, thanks!

**Comment by kupofgc** [comment]
Okay, another road block. Following the steps in my previous posts, the folder that I am trying to load onto the Pico is called "MiSTer_tty2pico-main" and it's 6.54MB. When I try to drag it onto the Pico drive, it says that it is too large as the new Pico drive is reading as only having 1.33MB of space. 

Not sure if I've download the correct file from the Github or not.

**Comment by kupofgc** [comment]
Ignore that last post, I figured where the correct files were. I have copied them over and am moving forward!

**Comment by kupofgc** [comment]
Okay, I'm at the part where I need to **"Change the tty in its .ini files to be the one for the device. Also turn off unsupported features. e.g."**

Where do I access this file on my MiSTer? When I access the ini setting under my Scripts, I don't see an option that relates to any of this.

**Comment by neil-morrison44** [comment]
For that bit follow the installation instructions for tty2oled - you should end up with a .ini file for that after they’re finished

**Comment by kupofgc** [comment]
I do have that file presumably, what I don't know is hwo to access and edit it.

Remove the microSD and open it on a PC through a text editor?
Somehow navigate to it and change it on the MiSTer?
Use an SSH?

I've tried all of these things. I used Putty to make an SSH connection, but after inputting the username and password, it just sits on a black screen waiting for an input so that option seems more difficult than is necessary.

**Comment by kupofgc** [comment]
Specifically, I don't know how to access the media/fat/tty2oled folder. I mean it's got to be obvious but I just can't figure it out.

**Comment by kupofgc** [comment]
Disregard my last comment, I was able to find the file on the microSD. It seems that I have done all the installation steps correctly at this point, but I am still not seeing an image on my LCD when running the MiSTer. I may just have to wait until the code specific display comes in the mail.

Thank you for all the help today. I will keep you posted as I move forward!

**Comment by kupofgc** [comment]
Actually, it seems that I missed a step.

**Add them to the drive that appears when the device is mounted along with main.py and the .mpy versions of the other files.**

I will work further on this. I'm not familiar with these file extensions and where I should find them. You can be more specific on what I need to do here? Thanks!

**Comment by neil-morrison44** [comment]
it should just be a case of taking the files inside the `files.zip` and putting them on the drive

But yeah - you'll need to plug in the display that the code's written for unless you adjust the code.

**Comment by kupofgc** [comment]
So just to clarify, I don't need to edit anything in the tty2pico files? The only thing that needed editing was the ini. for tty2oled.

Also, should the MiSTer logo pop up when the MiSTer is powered up? I just want to make sure I'm not missing anything and all the files are correct. When I open the main.py file in Thonny, the code reads:

from tty_and_logos import read_from_input, display_logo

display_logo("mister")
read_from_input()

Do I need to add anything to the paranthesis in the read_from_input line?

**Comment by neil-morrison44** [comment]
Correct, you don’t need to edit the files.

Once you’ve got the round display plugged in it should show the mister logo when turned on

**Comment by kupofgc** [comment]
Man that would be awesome, here's hoping everything is smooth sailing. It's got to travel across the pond from the UK, but I'll mark this closed as soon as I get it and get it hooked up!

**Comment by kupofgc** [comment]
So I finally got everything working after a bit of confusion on where certain pins needed to be connected. I am attaching some pictures in case anyone else gets confused. I had the 2021 Pico board with pre-installed headers and I think there are some different versions out there. 

Also, if using the same board and LCD, know that yon't have "MOSI" connector. Substitute that for you "DIN" connector. Likewise, there was no information stating where to hook up the "VCC" and "GND" connectors. There are multiple spots to hook up the "GND" on the PICO and if your board is different, hook your "VCC" up to the "3V3" header.

Thanks to @neil-morrison44 for this awesome build!

![FD79FEEA-A576-4EAF-B020-FD4BD00D1E01](https://user-images.githubusercontent.com/42288774/184683338-a4a17ba7-1cd3-4037-a97c-4a8336ccf0fe.jpg)
![IMG_3403](https://user-images.githubusercontent.com/42288774/184683357-1361cead-276f-48ba-ad77-670393013355.JPG)
![IMG_3404](https://user-images.githubusercontent.com/42288774/184683364-319c831a-d884-458f-b5f3-3ef8d0257861.JPG)
