### ISSUE TITLE
Scrambled image on display...

### ISSUE THREAD

**Issue by kupofgc** [neil-morrison44/MiSTer_tty2pico#3]
Hey everyone, 

Looking for some help with designing and creating logos for the cores. The original "mister.PNG" file works fine when booting up, but if I try to replace that file with a custom mister logo of my own, I get a static display. I used Photoshop to delete the background and make it transparent for my logo and also exported as a PNG. It must have something to do with the alpha channel as the walkthrough explicitly states that needs to be deleted, but as far as I can tell, I don't have one. FI anyone has used another program and has a walkthrough on how they created their logos, I'd love to hear it! 

I've attached a picture of the issue as well as my logo. Thanks!

![IMG_3402](https://user-images.githubusercontent.com/42288774/184685974-73320a9b-53f8-4bb5-91bc-4c9c9854a94b.jpg)
![mistertry](https://user-images.githubusercontent.com/42288774/184686184-b47021e8-addc-4128-a2ac-f01b49af2c23.png)

**Comment by kupofgc** [comment]
Update: I was able to get my images to start displaying once I added a black background instead of it being transparent. I'm still not having any luck with white backgrounds.

**Comment by neil-morrison44** [comment]
If you ssh in and run

```
screen /dev/ttyACM0
```

(Might need to change ACM0 to ACM1 or wherever the device is)

You should see the error message for each image that it tries, white background images should be fine

**Comment by kupofgc** [comment]
Thank you @neil-morrison44! Would you be able to double check that file name I need for a TurboGrafx16 logo? I have tried "turbografx16.png" as well as "TurboGrafx16.png" but can't get anything to load. It's not even flashing black like it's trying to load a new picture, so I don't think my file name is correct.

I'm very new SSH, so I'm still trying to figure that out. Thanks!

**Comment by neil-morrison44** [comment]
I believe it's "TGFX16.png", the `screen` command will tell you for sure though since it outputs what filename it tried to find

**Comment by kupofgc** [comment]
Thank you again. I need to find a good program and figure just exactly what you mean by SSH. I know it's a way to see what the MiSTer is doing, but I'm a total noob still in that area. If you have a good program you recommend, I'll use that and go from there. I have Mac and Windows.

**Comment by neil-morrison44** [comment]
You can ssh in using Terminal on your Mac or Command Prompt on windows - you'll need to look up the _how_ on your own, this'll help once you get a handle on it: https://boogermann.github.io/Bible_MiSTer/getting-started/network/network-access/

**Comment by kupofgc** [comment]
Thanks again, I'll check this out right now!
